ci:
  autoupdate_schedule: quarterly
  skip: [clang-format]

exclude: (?:^extern/)

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.0.1'
    hooks:
      - id: end-of-file-fixer
        exclude: |
          (?x)^(
            ^.*\.ai|
            ^.*\.txt\
            ^extern/
          )
      - id: trailing-whitespace
        exclude: |
          (?x)^(
            ^.*\.ai|
            ^.*\.txt|
            ^extern/|
            ^setup.cfg
          )
      - id: check-builtin-literals
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: requirements-txt-fixer
  - repo: https://github.com/asottile/pyupgrade
    rev: 'v2.20.0'
    hooks:
      - id: pyupgrade
        args:
          - --py36-plus
  - repo: https://github.com/PyCQA/isort
    rev: '5.9.1'
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: '21.6b0'
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: '3.9.2'
    hooks:
      - id: flake8
        args:
        - --show-source
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
# The following pre-commit hooks should only be run manually because they have
# dependencies that cannot be pip installed.
  - repo: local
    hooks:
    - id: clang-format
      stages: [manual]  # Requires clang-format.
      name: clang-format
      entry: clang-format
      language: system
      types: [c++]
      # Unclear if --style=file is necessary, it seems like clang-format uses
      # .clang-format if found by default, at least for newer versions. We
      # specify this here just in case.
      args:
      - --style=file
    - id: clang-tidy
      stages: [manual]  # Requires clang-tidy.
      name: clang-tidy
      entry: clang-tidy
      language: system
      types: [c++]
      # Exclude external files. Also exclude AABB.h because it uses intrinsics
      # heavily and these are not considered portable.
      exclude: |
        (?x)^(
          ^cpp/locality/AABB\.h|
          ^extern/
        )
      args:
      - --warnings-as-errors=*
    - id: cppcheck
      stages: [manual]  # Requires cppcheck.
      # Ignore external files and those taken verbatim from HOOMD.
      name: cppcheck
      entry: cppcheck
      language: system
      types: [c++]
      # Exclude external files. Also exclude AABB.h because it uses intrinsics
      # heavily and these are not considered portable.
      exclude: |
        (?x)^(
          ^cpp/locality/AABB\.h|
          ^extern/
        )
      args:
      - cpp/
      - --enable=warning,style,performance,portability # Ignore unused (could be used by Cython).
      - --std=c++14
      - --language=c++ # Force C++ for .h header files.
      - --inline-suppr # Enable inline suppresions of warnings.
      - --suppress=*:cpp/locality/AABB.h
      - --suppress=*:extern/*
      - --error-exitcode=1
