name: Build wheels

on:
  # Trigger on pull requests.
  pull_request:

  # Trigger on pushes to the mainline branches and version tags. This prevents building commits
  # twice when the pull request source branch is in the same repository.
  push:
    branches:
      - "maint"
      - "master"
    tags:
      - "v*"

  # Trigger on request.
  workflow_dispatch:

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  build_wheels:
    name: Build wheel for ${{ matrix.os }}, Python ${{ matrix.pyver }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019] #ubuntu-20.04, macos-10.15]
        pyver: [3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: "recursive"

      # Configure compilers for Windows. Does nothing on Linux/Mac.
      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build wheels
        uses: joerick/cibuildwheel@v1.10.0
        env:
          # Build for cpython >= 3.6.
          CIBW_PROJECT_REQUIRES_PYTHON: "==${{ matrix.pyver }}.*"
          CIBW_SKIP: pp*

          # Build only on 64-bit architectures.
          CIBW_ARCHS_MACOS: x86_64
          CIBW_ARCHS_LINUX: auto64
          CIBW_ARCHS_WINDOWS: auto64

          # Configure environment variables.
          CIBW_ENVIRONMENT_LINUX: "CMAKE_PREFIX_PATH=/project/tbb LD_LIBRARY_PATH=/project/tbb/lib/intel64/gcc4.8:$LD_LIBRARY_PATH"
          CIBW_ENVIRONMENT_MACOS: "CMAKE_PREFIX_PATH=/Users/runner/work/freud/freud/tbb LD_LIBRARY_PATH=/Users/runner/work/freud/freud/tbb/lib/intel64/gcc4.8:$LD_LIBRARY_PATH"

          # Set up TBB.
          CIBW_BEFORE_BUILD_LINUX: "source .github/workflows/cibuildwheel-before-build.sh {package} linux"
          CIBW_BEFORE_BUILD_MACOS: "source .github/workflows/cibuildwheel-before-build.sh {package} macos"
          CIBW_BEFORE_BUILD_WINDOWS: "powershell .github/workflows/cibuildwheel-before-build.ps1 {package}"

          # Repair the wheels.
          # This is only needed on Windows; cibuildwheel repairs correctly on Linux/Mac.
          CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: "powershell .github/workflows/cibuildwheel-repair-wheel.ps1 \"{dest_dir}\" \"{wheel}\""

          # Test the wheels.
          CIBW_BEFORE_TEST_LINUX: "source .github/workflows/cibuildwheel-before-test.sh {package}"
          CIBW_BEFORE_TEST_MACOS: "source .github/workflows/cibuildwheel-before-test.sh {package}"
          CIBW_BEFORE_TEST_WINDOWS: "powershell .github/workflows/cibuildwheel-before-test.ps1 {package}"
          CIBW_TEST_COMMAND_LINUX: "cd {project}/tests && python -m pytest . -v --log-level=DEBUG --rootdir={project}/tests"
          CIBW_TEST_COMMAND_MACOS: "cd {project}/tests && python -m pytest . -v --log-level=DEBUG --rootdir={project}/tests"
          CIBW_TEST_COMMAND_WINDOWS: "cd {project}/tests && python -c \"import freud; print(freud.__version__)\""

      - uses: actions/upload-artifact@v2.2.3
        with:
          name: dist
          path: ./wheelhouse/*.whl

#     - name: Setup tmate session
#       if: ${{ failure() }}
#       uses: mxschmitt/action-tmate@v3
#       timeout-minutes: 60

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: actions/setup-python@v2.2.2
        name: Install Python
        with:
          python-version: '3.9'

      - name: Install build requirements
        run: python3 -m pip --disable-pip-version-check install scikit-build cmake -r requirements.txt --upgrade --progress-bar=off

      - name: Build sdist
        run: python setup.py sdist

      - uses: actions/upload-artifact@v2.2.3
        with:
          name: dist
          path: dist/*.tar.gz

  upload_pypi:
    name: Publish [PyPI]
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2.0.9
        with:
          name: dist
          path: dist

      - name: Check files
        run: ls -lR dist

      - name: Upload to PyPI
        # upload to PyPI on every tag starting with 'v'
        if: startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Upload to TestPyPI
        # otherwise, upload to TestPyPi when secrets are available
        if: ${{ !startsWith(github.ref, 'refs/tags/v') && (github.event_name != 'pull_request' || (github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]')) }}
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true

      - name: Slack notification
        if: startsWith(github.ref, 'refs/tags/v') && always()
        uses: act10ns/slack@v1.2.2
        with:
          status: ${{ job.status }}
          channel: '#dev-freud'
